src/routes/api.py
"""
Routing for API.
"""

# Import python modules.
import os
import pickle
from typing import List
from datetime import datetime
from flask import Blueprint, request, url_for, redirect, render_template
from werkzeug.utils import secure_filename

# Import created modules.
from src import db, srcdir
from src.models.sentiment import Sentiment
from src.model import normalize_text, vectorizer_tf

# Load model from pickled file
vectorizer = vectorizer_tf

model_path = os.path.join(srcdir, os.environ.get('MODEL_FILE', 'model.pkl'))
model = pickle.load(open(model_path, 'rb'))

# Make the blueprint.
api_route = Blueprint('api_route', __name__, url_prefix='/api/v1')

"""
--------------------------------------------------------------
# Sentiment Api Routes.
--------------------------------------------------------------
"""
@api_route.route("create-sentiment", methods=['POST'])
def create_sentiment():
    """
    Description:
    ------------
    Add a new sentiment to the database.

    Path:
    -----
    POST /api/v1/create-sentiments
    
    Request Body:
    -------------
    text : str
        The content of the sentiment data.
    created_at : datetime
        The creation date of the sentiment data.
    file : file
        The file containing multiple sentiment data.
    """
    from src.app import app
    
    if request.method == 'POST':
        try:
            # Process uploaded file. Assume the file is in csv format.
            if request.files["file"].filename != "":
                
                # Save the file.
                file = request.files["file"]
                filepath = os.path.join(app.config["UPLOAD_FOLDER"], secure_filename(file.filename))
                file.save(filepath)
                
                # Process file content. The content of the file should be in the following format:
                # Text, Created At(Optional)
                with open(filepath, 'r') as f:
                    for line in f.read().splitlines():
                        sentiment_content = line.split(',')
                        # Construct the sentiment object and add it to the database.
                        norm_text = normalize_text(sentiment_content[0].strip())
                        vec_sentiment = vectorizer.transform([norm_text])
                        prediction = model.predict(vec_sentiment)

                        if prediction[0] == 0:
                            sen = "Positive"
                        else :
                            sen = "Negative"
                        sentiment = Sentiment(
                            sentiment = sen,
                            text = sentiment_content[0].strip()
                        )
                        if len(sentiment_content) > 1:
                            sentiment.created_at = datetime.strptime(
                                sentiment_content[1].strip(), '%Y-%m-%d %H:%M:%S'
                            )
                        db.session.add(sentiment)
                        db.session.commit()    
                return redirect(url_for('webpage_route.dashboard'))    
            
            # Process form data.
            elif request.form["text"] != "":
                
                # Construct the sentiment data and save it to the database.
                norm_text = normalize_text(request.form['text'].strip())
                vec_sentiment = vectorizer.transform([norm_text])
                prediction = model.predict(vec_sentiment)
                if prediction[0] == 0:
                    sen = "Positive"
                else :
                    sen = "Negative"

                sentiment = Sentiment(
                    sentiment = sen,
                    text = request.form['text'].strip()
                )
                if request.form['created_at']:
                    sentiment.created_at = datetime.strptime(
                        request.form['created_at'].strip(), '%Y-%m-%dT%H:%M'
                    )
                db.session.add(sentiment)
                db.session.commit()
                return redirect(url_for('webpage_route.dashboard'))
            
            # No data provided.
            else:
                raise Exception("No data provided.")

        except Exception as err:
            return render_template('pages/add-data.html', error = err, form = request.form)

@api_route.route("/delete-sentiment/<int:id>", methods=["POST"])
def delete_sentiment(id):
    """
    Description:
    ------------
    Delete a sentiment from the database.
    
    Path:
    -----
    api/v1/delete-sentiment/<int:id>
    """
    
    # Delete the sentiment from the database if it exists.
    try:        
        sentiment = Sentiment.query.get(id)
        if sentiment is not None:
            db.session.delete(sentiment)
            db.session.commit()
        return redirect(url_for('webpage_route.dashboard'))
    
    except Exception as err:
        sentiments: List[Sentiment] = Sentiment.query.all()
        return render_template('pages/dashboard.html', error = err, sentiments = sentiments)

src/templates/pages/add-data.html
{% extends 'layouts/base.html' %} 
{% set active_page = 'add-data' %}

{% block title %} 
	Add Data
{% endblock %}

{% block heading %} 
	<h2 class="sentiment-title">Add Data</h2>
	<p class="sentiment-subtitle">Add new sentiment data</p>
{% endblock %}

{% block content %}

<div class="row mt-3">
    <div class="col-12 mt-2">
        {% if error %}
            <div class="d-block">	
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <i>{{ error }}</i>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        {% endif %}
        <form action="{{ url_for('api_route.create_sentiment') }}" enctype="multipart/form-data" method="POST">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="text">Text</label>
                                <textarea name="text" id="text" cols="30" rows="4"
                                    class="form-control">{{ form.text if form }}</textarea>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="created_at">DateTime</label>
                                <input type="datetime-local" class="form-control" id="created_at" aria-describedby="name" name="created_at"/>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="hr-sect text-muted"> 
                                Atau upload banyak data dengan CSV
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="file">File</label>
                                <input type="file" accept=".csv" class="form-control pt-1" id="file" aria-describedby="file" name="file"/>
                                <small class="text-muted"> Format input yang diterima: .csv </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col">
                    <button type="submit" class="btn btn-success btn-block px-5"> Submit Data </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

src/templates/pages/contributor.html
{% extends 'layouts/base.html' %} 
{% set active_page = 'contributor' %}

{% block title %} 
	Contributor
{% endblock %}

{% block heading %} 
	<h2 class="sentiment-title">Contributor</h2>
	<p class="sentiment-subtitle">The contributor of the website and sentiment analysis model</p>
{% endblock %}

{% block content %}
<div class="page-contributor">
    <ol>
        <li> 
            &nbsp;Reihan Andhika Putra - 13519043  
            <br>
        </li>
        <li> 
            &nbsp;Dzaki Muhammad - 13519049 
            <br>
        </li>
        <li> 
            &nbsp;Naufal Yahya Kurnianto - 13519141 
            <br>
        </li>
    </ol>
</div>
{% endblock %}

src/templates/pages/dashboard.html
{% extends 'layouts/base.html' %} 
{% set active_page = 'dashboard' %}

{% block title %} 
	Sentiment Dashboard
{% endblock %}

{% block heading %} 
	<h2 class="sentiment-title">Dashboard</h2>
	<p class="sentiment-subtitle">View the summary of sentiment data </p>
{% endblock %}

{% block content %}
<div class="row mt-3 mr-2">
    <div class="col-12 mt-2">
		{% if error %}
			<div class="d-block">	
				<div class="alert alert-danger alert-dismissible fade show" role="alert">
					<i>{{ error }}</i>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			</div>
		{% endif %}
		<div class="card">
			<div class="card-body">
				{% if error %}
					<div class="row col-12 mx-2 d-block">	
						<div class="alert alert-danger alert-dismissible fade show" role="alert">
								<p> {{ error }}</p>
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
						</div>
					</div>
				{% endif %}
				<div class="row table-wrapper">
					<table class="table mx-4 my-2 table-responsive-md">
						<thead style="border-top: none; !important">
						<tr class="text-muted">
							<th scope="col" style="width:5%"></th>
							<th scope="col" style="width:75%">TEXT</th>
							<th scope="col" style="width:15%">SENTIMENT</th>
							<th scope="col" style="width:5%"></th>
						</tr>
						</thead>
						<tbody>
							{% for sentiment in sentiments %}
								<tr>
									<td>{{ loop.index }}</td>
									<td>
										<div> {{ sentiment.text }} <div> 
										<small class="text-muted"> {{sentiment.created_at.strftime("%d %B %Y, %-I:%M:%S %p")}} </small>
									</td>
									<td>
										{% if sentiment.sentiment == 'Positive' %}
											<span class="badge badge-success"> {{ sentiment.sentiment }} </span>
										{% elif sentiment.sentiment == 'Negative' %}
											<span class="badge badge-danger"> {{ sentiment.sentiment }} </span>
										{% endif%}
									</td>
									<td>
										<form action="{{ url_for('api_route.delete_sentiment', id=sentiment.id) }}" method="POST">
											<button type="submit" class="btn btn-warning"><span class="fa fa-trash"></span></a>
										</form> 
										
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}