src/routes/webpage.py
"""
Routing for the webpages.
"""

# Import python modules.
from typing import List
from flask import Blueprint, render_template

# Import created modules.
from src import db
from src.models.sentiment import Sentiment

# Make the blueprint.
webpage_route = Blueprint('webpage_route', __name__, url_prefix='/')


"""
--------------------------------------------------------------
# Sentiment Tracker Webpages.
--------------------------------------------------------------
"""
@webpage_route.route("dashboard")
def dashboard():
    """
    Description:
    ------------
    Sentiment tracker webpage.
    """
    sentiments: List[Sentiment] = Sentiment.query.all()
    return render_template('pages/dashboard.html', sentiments=sentiments)

@webpage_route.route("add-data")
def add_data():
    """
    Description:
    ------------
    Add sentiment data webpage.
    """
    return render_template('pages/add-data.html')

@webpage_route.route("contributor")
def contributor():
    """
    Description:
    ------------
    Website contributor webpage.
    """

    return render_template('pages/contributor.html')
    

src/templates/includes/navbar.html
<nav class="navbar navbar-sentiment navbar-expand-lg navbar-light fixed-top" data-aos="fade-down">
	<button class="btn btn-secondary d-md-none mr-auto mr-2" id="menu-toggle"> &laquo; Menu
	</button>
</nav>

src/templates/includes/script.html
<!-- Bootstrap core JavaScript -->
<script src="{{ url_for('static', filename='vendor/jquery/jquery.slim.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}">
</script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
	AOS.init();
</script>
<!-- Utility -->
<script src="{{ url_for('static', filename='scripts/utility.js') }}"></script>
<!-- Menu Toggle Script -->
<script>
	// For toggling sidebar.
	$("#menu-toggle").click(function (e) {
		e.preventDefault();
		$("#wrapper").toggleClass("toggled");
	});
</script>

src/templates/includes/sidebar.html
<div class="border-right" id="sidebar-wrapper">
	<div class="sidebar-heading text-center">
		<img src="{{ url_for('static', filename='images/sentiment-analysis.png') }}" alt=""
			class="my-4 logo-sentiment" />
	</div>
	<div class="list-group list-group-flush">
		<a href="{{ url_for('webpage_route.dashboard') }}" class="list-group-item list-group-item-action {{ 'active' if active_page == 'dashboard'}}"> Dashboard </a>
		<a href="{{ url_for('webpage_route.add_data') }}" class="list-group-item list-group-item-action {{ 'active' if active_page == 'add-data'}}"> Add Data </a>
		<a href="{{ url_for('webpage_route.contributor') }}" class="list-group-item list-group-item-action {{ 'active' if active_page == 'contributor'}}"> Contributor </a>
	</div>
</div>

src/templates/includes/style.html
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
<link href="{{ url_for('static', filename='styles/main.css') }}" rel="stylesheet" />
<script src="https://kit.fontawesome.com/7daea7707d.js" crossorigin="anonymous"></script>